language: perl
matrix:
  include:
    - perl: "5.30"
    - perl: "5.30-thr"
    - perl: "5.28"
    - perl: "5.26"
    - perl: "5.24"
    - perl: "5.22"
    - perl: "5.20"
      dist: trusty
    - perl: "5.18"
      dist: trusty
    - perl: "5.16"
      dist: trusty
    - perl: "5.14"
      dist: trusty
    - perl: "5.12"
      dist: trusty
    - perl: "5.10"
      dist: trusty
    - perl: "5.8.9"
      dist: trusty
    - perl: "5.8.9-thr"
      dist: trusty
    - perl: "5.8.1"
      dist: trusty
    - perl: "5.6.2"
      dist: trusty
    - perl: "5.6.1"
      dist: trusty
      script: prove -r -Ilib -Iinc -Iinc/archaic $(test-dirs)      
    - perl: "dev"
    - perl: "dev-thr"
    - perl: "blead"
  allow_failures:
    - perl: "blead"
before_install:
  - export DIST_INKT_PROFILE="Dist::Inkt::Profile::TOBYINK"
  - eval $(curl https://travis-perl.github.io/init) --auto
install:
  - cpan-install --toolchain
  - cpan-install --deps
  - cpan-install --coverage
  - '[ -n "$MOOSE_RELEASE" ] && cpan-install "$MOOSE_RELEASE" || echo "MOOSE_RELEASE is not set"'
  - '[ -n "$EC_RELEASE" ]    && cpan-install "$EC_RELEASE"    || echo "EC_RELEASE is not set"'
  - '[ -n "$MOO_RELEASE" ]   && cpan-install "$MOO_RELEASE"   || echo "MOO_RELEASE is not set"'
before_script:
  - coverage-setup
script:
  - prove -r -Ilib -Iinc $(test-dirs)
after_success:
  - coverage-report
cache:
  directories:
    - "~/perl5"
